### ISSUE TITLE
Hard reset of the 3 last commit on master

### ISSUE THREAD

**Issue by matlo607** [dougbradbury/cslim#33]
Hello @dougbradbury,

As I told you in https://github.com/dougbradbury/cslim/pull/30, I was working on this branch and the fixes were not ready to be merged yet.
Could you please reset hard the 3 commits from master ?
- d927ab5e133909c137b15c5d6a1b540bd818c9e9
- 19e4422e42aaf1b0224317fe85109ee617189de6
- 70ac34a0184d2e1d085e1d3c7a874701826101df

I know it is a **very bad practice** to do so but otherwise, it would screw the history.
I think nobody has cloned the repository in the meantime.
```
git checkout master
git reset --hard HEAD~3
git log // visual check
git push -f origin master
```

**Comment by dougbradbury** [comment]
done

**Comment by matlo607** [comment]
Hello @dougbradbury,

It seems you reverted more than we really wanted at the beginning.
Please compare with what I have on my [repository](https://github.com/matlo607/cslim/commits/master).

The following commits are missing :
- [VS2017] fix error C2016: C requires that a struct or union has at least one member
- [VS2013] error C3861: snprintf identifier not found
- ...
- use Serialies Release functino for free memory
- Merge branch 'fix-build-visual-studio-2017' of github.com:matlo607/cs… 
- move snprintf fixes to a compatibility file

I may have missed some of them.
What exactly happened there ?
